python script_30012026_baseline_v3_related.py \
  --path /work/vajira/DATA/EXG_PTB_XL/physionet/files/ptb-xl/1_0_1 \
  --batch_size 3 \
  --sampling_rate 500 \
  --epochs 1 \
  --n_pos_viz 10 \
  --n_neg_viz 10 \
  --viz_random \
  --out_dir runs/mi_vs_norm_imn \
  --wandb_project mesormorphic_ecg \
  --early_stop_patience 10 \
  --scheduler step \
  --viz_topk \
  --viz_mc_dropout \
  --verbose